### ISSUE TITLE
import statement not working

### ISSUE THREAD

**Issue by NicolasAG** [bhoov/spacyface#4]
Hi,
Thanks for making this package public.
I tried to use it however it did not work when I tried to import it.
I installed with `pip install spacyface`
These were my steps:
```
Python 3.8.7 (default, Jan 12 2021, 17:06:28)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from aligner import BertAligner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'aligner'
>>>
>>> from spacyface import BertAligner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/.local/lib/python3.8/site-packages/spacyface/__init__.py", line 1, in <module>
    from .aligner import (
  File "/tmp/.local/lib/python3.8/site-packages/spacyface/aligner.py", line 26, in <module>
    from .utils.f import flatten_, assoc, delegates
ModuleNotFoundError: No module named 'spacyface.utils'
>>>
>>> from spacyface.aligner import BertAligner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/.local/lib/python3.8/site-packages/spacyface/__init__.py", line 1, in <module>
    from .aligner import (
  File "/tmp/.local/lib/python3.8/site-packages/spacyface/aligner.py", line 26, in <module>
    from .utils.f import flatten_, assoc, delegates
ModuleNotFoundError: No module named 'spacyface.utils'
>>>
>>> import spacyface
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/.local/lib/python3.8/site-packages/spacyface/__init__.py", line 1, in <module>
    from .aligner import (
  File "/tmp/.local/lib/python3.8/site-packages/spacyface/aligner.py", line 26, in <module>
    from .utils.f import flatten_, assoc, delegates
ModuleNotFoundError: No module named 'spacyface.utils'
>>>
```

**Comment by bhoov** [comment]
What version of `spacyface` is installed on your system? (`pip freeze | grep spacyface`)

This looks eerily like issue #3, but was fixed in PR #2

**Comment by NicolasAG** [comment]
indeed sorry for not seeing that earlier.
`pip install spacyface` installed version `0.1.5`.

**Comment by NicolasAG** [comment]
I guess the issue then is that pip install does not install the latest version and that when I specify `==0.2.2` it doesn't work either
```
pip install spacyface==0.2.2

ERROR: Could not find a version that satisfies the requirement spacyface==0.2.2
ERROR: No matching distribution found for spacyface==0.2.2
```

**Comment by bhoov** [comment]
Can you try `pip install -U spacyface`?

**Comment by NicolasAG** [comment]
`-U` doesn't work either.
I tried to install from source like this:
```
git clone https://github.com/bhoov/spacyface.git /spacyface
cd /spacyface && pip install .
```
but then I get `ERROR: Package 'spacyface' requires a different Python: 3.8.7 not in '<3.8,>=3.6'`
