### ISSUE TITLE
ModuleNotFoundError: No module named 'spacyface.utils'

### ISSUE THREAD

**Issue by tceron** [bhoov/spacyface#7]
I've installed the latest version 0.1.5, though I keep getting the same error as #3 . 

The code is below: 
```
from spacyface import BertAligner

sequence = "The weather is really great. Let's go for a walk."
alnr = BertAligner.from_pretrained("bert-base-cased")
tokens = alnr.meta_tokenize(sequence)
token_data = [{'token': tok.token, 'feature': tok.pos} for tok in tokens]
print(pd.DataFrame(token_data))
```

Error: 
```
Traceback (most recent call last):
  File "/mount/...dataset.py", line 16, in <module>
    from spacyface import BertAligner
  File "/mount/.../venv_reps/lib64/python3.10/site-packages/spacyface/__init__.py", line 1, in <module>
    from .aligner import (
  File "/mount/.../venv_reps/lib64/python3.10/site-packages/spacyface/aligner.py", line 26, in <module>
    from .utils.f import flatten_, assoc, delegates
ModuleNotFoundError: No module named 'spacyface.utils'

```
Thanks in advance!

**Comment by tceron** [comment]
It works correctly when I git clone the repository and move the "spacyface" subfolder to my project folder. Problem solved on my side.

**Comment by bhoov** [comment]
Apologies for the headache! Yes, your solution will work. I also forgot one important line in the setup. You can also just run `pip install -e .` to install spacyface to your current python environment. I have updated the README, fixed by 5265e9e8f645f86a2653c65f5d017ec2930e8009.
